baseURL = "https://laurabolta.github.io/"
title   = "Laura Boltà Ballesteros"

[module]
  [[module.imports]]
    path = "github.com/hugo-toha/toha/v4"

[params]
  background = "/images/site/greycolor.png"