name: Deploy to laurabolta.github.io

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo (extended)
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.151.0'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Prepare npm deps from Hugo modules
        run: hugo mod npm pack

      - name: Install npm dependencies
        run: npm ci

      - name: Build site
        run: hugo --gc --minify

      - name: Deploy to laurabolta.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          external_repository: laurabolta/laurabolta.github.io
          publish_dir: ./public
          publish_branch: main
